/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateAttachmentDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-08T11:03:08.533Z")
public class CreateAttachmentDto {
  @SerializedName("title")
  private String title = null;

  @SerializedName("fileMime")
  private String fileMime = null;

  @SerializedName("fileData")
  private String fileData = null;

  @SerializedName("logId")
  private Integer logId = null;

  public CreateAttachmentDto title(String title) {
    this.title = title;
    return this;
  }

   /**
   * What kind of log is it?
   * @return title
  **/
  @ApiModelProperty(example = "run", required = true, value = "What kind of log is it?")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CreateAttachmentDto fileMime(String fileMime) {
    this.fileMime = fileMime;
    return this;
  }

   /**
   * What kind of log is it?
   * @return fileMime
  **/
  @ApiModelProperty(example = "run", required = true, value = "What kind of log is it?")
  public String getFileMime() {
    return fileMime;
  }

  public void setFileMime(String fileMime) {
    this.fileMime = fileMime;
  }

  public CreateAttachmentDto fileData(String fileData) {
    this.fileData = fileData;
    return this;
  }

   /**
   * What kind of log is it?
   * @return fileData
  **/
  @ApiModelProperty(example = "23144132412314344", required = true, value = "What kind of log is it?")
  public String getFileData() {
    return fileData;
  }

  public void setFileData(String fileData) {
    this.fileData = fileData;
  }

  public CreateAttachmentDto logId(Integer logId) {
    this.logId = logId;
    return this;
  }

   /**
   * The id of the corresponding Log
   * @return logId
  **/
  @ApiModelProperty(example = "1", required = true, value = "The id of the corresponding Log")
  public Integer getLogId() {
    return logId;
  }

  public void setLogId(Integer logId) {
    this.logId = logId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAttachmentDto createAttachmentDto = (CreateAttachmentDto) o;
    return Objects.equals(this.title, createAttachmentDto.title) &&
        Objects.equals(this.fileMime, createAttachmentDto.fileMime) &&
        Objects.equals(this.fileData, createAttachmentDto.fileData) &&
        Objects.equals(this.logId, createAttachmentDto.logId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, fileMime, fileData, logId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAttachmentDto {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    fileMime: ").append(toIndentedString(fileMime)).append("\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("    logId: ").append(toIndentedString(logId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

