/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateSubSystemPermissionDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-08T11:03:08.533Z")
public class CreateSubSystemPermissionDto {
  @SerializedName("user")
  private Object user = null;

  @SerializedName("subsystem")
  private Object subsystem = null;

  @SerializedName("isMember")
  private Boolean isMember = null;

  @SerializedName("editEorReason")
  private Boolean editEorReason = null;

  @SerializedName("subSystemHash")
  private String subSystemHash = null;

  @SerializedName("subSystemTokenDescription")
  private String subSystemTokenDescription = null;

  public CreateSubSystemPermissionDto user(Object user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(required = true, value = "")
  public Object getUser() {
    return user;
  }

  public void setUser(Object user) {
    this.user = user;
  }

  public CreateSubSystemPermissionDto subsystem(Object subsystem) {
    this.subsystem = subsystem;
    return this;
  }

   /**
   * Get subsystem
   * @return subsystem
  **/
  @ApiModelProperty(required = true, value = "")
  public Object getSubsystem() {
    return subsystem;
  }

  public void setSubsystem(Object subsystem) {
    this.subsystem = subsystem;
  }

  public CreateSubSystemPermissionDto isMember(Boolean isMember) {
    this.isMember = isMember;
    return this;
  }

   /**
   * If the user is a member.
   * @return isMember
  **/
  @ApiModelProperty(example = "true", required = true, value = "If the user is a member.")
  public Boolean isIsMember() {
    return isMember;
  }

  public void setIsMember(Boolean isMember) {
    this.isMember = isMember;
  }

  public CreateSubSystemPermissionDto editEorReason(Boolean editEorReason) {
    this.editEorReason = editEorReason;
    return this;
  }

   /**
   * Reason for the end of run.
   * @return editEorReason
  **/
  @ApiModelProperty(example = "true", required = true, value = "Reason for the end of run.")
  public Boolean isEditEorReason() {
    return editEorReason;
  }

  public void setEditEorReason(Boolean editEorReason) {
    this.editEorReason = editEorReason;
  }

  public CreateSubSystemPermissionDto subSystemHash(String subSystemHash) {
    this.subSystemHash = subSystemHash;
    return this;
  }

   /**
   * A unique token for a subsystem linked to a user.
   * @return subSystemHash
  **/
  @ApiModelProperty(example = "0f62642f-a46c-4c3a-925f-5070d8b0594e", required = true, value = "A unique token for a subsystem linked to a user.")
  public String getSubSystemHash() {
    return subSystemHash;
  }

  public void setSubSystemHash(String subSystemHash) {
    this.subSystemHash = subSystemHash;
  }

  public CreateSubSystemPermissionDto subSystemTokenDescription(String subSystemTokenDescription) {
    this.subSystemTokenDescription = subSystemTokenDescription;
    return this;
  }

   /**
   * A description for the subsystem.
   * @return subSystemTokenDescription
  **/
  @ApiModelProperty(example = "Read and Write token for subsystem", required = true, value = "A description for the subsystem.")
  public String getSubSystemTokenDescription() {
    return subSystemTokenDescription;
  }

  public void setSubSystemTokenDescription(String subSystemTokenDescription) {
    this.subSystemTokenDescription = subSystemTokenDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSubSystemPermissionDto createSubSystemPermissionDto = (CreateSubSystemPermissionDto) o;
    return Objects.equals(this.user, createSubSystemPermissionDto.user) &&
        Objects.equals(this.subsystem, createSubSystemPermissionDto.subsystem) &&
        Objects.equals(this.isMember, createSubSystemPermissionDto.isMember) &&
        Objects.equals(this.editEorReason, createSubSystemPermissionDto.editEorReason) &&
        Objects.equals(this.subSystemHash, createSubSystemPermissionDto.subSystemHash) &&
        Objects.equals(this.subSystemTokenDescription, createSubSystemPermissionDto.subSystemTokenDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, subsystem, isMember, editEorReason, subSystemHash, subSystemTokenDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSubSystemPermissionDto {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    subsystem: ").append(toIndentedString(subsystem)).append("\n");
    sb.append("    isMember: ").append(toIndentedString(isMember)).append("\n");
    sb.append("    editEorReason: ").append(toIndentedString(editEorReason)).append("\n");
    sb.append("    subSystemHash: ").append(toIndentedString(subSystemHash)).append("\n");
    sb.append("    subSystemTokenDescription: ").append(toIndentedString(subSystemTokenDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

