/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * CreateRunResultDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-08T11:03:08.533Z")
public class CreateRunResultDto {
  @SerializedName("timeO2Start")
  private OffsetDateTime timeO2Start = null;

  @SerializedName("timeTrgStart")
  private OffsetDateTime timeTrgStart = null;

  @SerializedName("timeO2End")
  private OffsetDateTime timeO2End = null;

  @SerializedName("timeTrgEnd")
  private OffsetDateTime timeTrgEnd = null;

  @SerializedName("runType")
  private String runType = null;

  @SerializedName("runQuality")
  private String runQuality = null;

  @SerializedName("activityId")
  private String activityId = null;

  @SerializedName("nDetectors")
  private Integer nDetectors = null;

  @SerializedName("nFlps")
  private Integer nFlps = null;

  @SerializedName("nEpns")
  private Integer nEpns = null;

  @SerializedName("nTimeframes")
  private Integer nTimeframes = null;

  @SerializedName("nSubtimeframes")
  private Integer nSubtimeframes = null;

  @SerializedName("bytesReadOut")
  private Integer bytesReadOut = null;

  @SerializedName("bytesTimeframeBuilder")
  private Integer bytesTimeframeBuilder = null;

  @SerializedName("runNumber")
  private Integer runNumber = null;

  public CreateRunResultDto timeO2Start(OffsetDateTime timeO2Start) {
    this.timeO2Start = timeO2Start;
    return this;
  }

   /**
   * Get timeO2Start
   * @return timeO2Start
  **/
  @ApiModelProperty(example = "2018-11-26T16:43:22.279Z", required = true, value = "")
  public OffsetDateTime getTimeO2Start() {
    return timeO2Start;
  }

  public void setTimeO2Start(OffsetDateTime timeO2Start) {
    this.timeO2Start = timeO2Start;
  }

  public CreateRunResultDto timeTrgStart(OffsetDateTime timeTrgStart) {
    this.timeTrgStart = timeTrgStart;
    return this;
  }

   /**
   * Get timeTrgStart
   * @return timeTrgStart
  **/
  @ApiModelProperty(example = "2018-11-26T16:43:22.279Z", required = true, value = "")
  public OffsetDateTime getTimeTrgStart() {
    return timeTrgStart;
  }

  public void setTimeTrgStart(OffsetDateTime timeTrgStart) {
    this.timeTrgStart = timeTrgStart;
  }

  public CreateRunResultDto timeO2End(OffsetDateTime timeO2End) {
    this.timeO2End = timeO2End;
    return this;
  }

   /**
   * Get timeO2End
   * @return timeO2End
  **/
  @ApiModelProperty(example = "2018-11-26T16:43:22.279Z", required = true, value = "")
  public OffsetDateTime getTimeO2End() {
    return timeO2End;
  }

  public void setTimeO2End(OffsetDateTime timeO2End) {
    this.timeO2End = timeO2End;
  }

  public CreateRunResultDto timeTrgEnd(OffsetDateTime timeTrgEnd) {
    this.timeTrgEnd = timeTrgEnd;
    return this;
  }

   /**
   * Get timeTrgEnd
   * @return timeTrgEnd
  **/
  @ApiModelProperty(example = "2018-11-26T16:43:22.279Z", required = true, value = "")
  public OffsetDateTime getTimeTrgEnd() {
    return timeTrgEnd;
  }

  public void setTimeTrgEnd(OffsetDateTime timeTrgEnd) {
    this.timeTrgEnd = timeTrgEnd;
  }

  public CreateRunResultDto runType(String runType) {
    this.runType = runType;
    return this;
  }

   /**
   * What kind of run.
   * @return runType
  **/
  @ApiModelProperty(example = "", required = true, value = "What kind of run.")
  public String getRunType() {
    return runType;
  }

  public void setRunType(String runType) {
    this.runType = runType;
  }

  public CreateRunResultDto runQuality(String runQuality) {
    this.runQuality = runQuality;
    return this;
  }

   /**
   * The quality of the run.
   * @return runQuality
  **/
  @ApiModelProperty(example = "", required = true, value = "The quality of the run.")
  public String getRunQuality() {
    return runQuality;
  }

  public void setRunQuality(String runQuality) {
    this.runQuality = runQuality;
  }

  public CreateRunResultDto activityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

   /**
   * The id of the activity.
   * @return activityId
  **/
  @ApiModelProperty(example = "Sl4e12ofb83no92ns", required = true, value = "The id of the activity.")
  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public CreateRunResultDto nDetectors(Integer nDetectors) {
    this.nDetectors = nDetectors;
    return this;
  }

   /**
   * Number of detectors during run.
   * @return nDetectors
  **/
  @ApiModelProperty(example = "16", required = true, value = "Number of detectors during run.")
  public Integer getNDetectors() {
    return nDetectors;
  }

  public void setNDetectors(Integer nDetectors) {
    this.nDetectors = nDetectors;
  }

  public CreateRunResultDto nFlps(Integer nFlps) {
    this.nFlps = nFlps;
    return this;
  }

   /**
   * Number of FLPs that computed data
   * @return nFlps
  **/
  @ApiModelProperty(example = "7", required = true, value = "Number of FLPs that computed data")
  public Integer getNFlps() {
    return nFlps;
  }

  public void setNFlps(Integer nFlps) {
    this.nFlps = nFlps;
  }

  public CreateRunResultDto nEpns(Integer nEpns) {
    this.nEpns = nEpns;
    return this;
  }

   /**
   * Number of EPNs that stored data
   * @return nEpns
  **/
  @ApiModelProperty(example = "8", required = true, value = "Number of EPNs that stored data")
  public Integer getNEpns() {
    return nEpns;
  }

  public void setNEpns(Integer nEpns) {
    this.nEpns = nEpns;
  }

  public CreateRunResultDto nTimeframes(Integer nTimeframes) {
    this.nTimeframes = nTimeframes;
    return this;
  }

   /**
   * Number of timeframes
   * @return nTimeframes
  **/
  @ApiModelProperty(example = "2", required = true, value = "Number of timeframes")
  public Integer getNTimeframes() {
    return nTimeframes;
  }

  public void setNTimeframes(Integer nTimeframes) {
    this.nTimeframes = nTimeframes;
  }

  public CreateRunResultDto nSubtimeframes(Integer nSubtimeframes) {
    this.nSubtimeframes = nSubtimeframes;
    return this;
  }

   /**
   * Number of subtimeframes
   * @return nSubtimeframes
  **/
  @ApiModelProperty(example = "4", required = true, value = "Number of subtimeframes")
  public Integer getNSubtimeframes() {
    return nSubtimeframes;
  }

  public void setNSubtimeframes(Integer nSubtimeframes) {
    this.nSubtimeframes = nSubtimeframes;
  }

  public CreateRunResultDto bytesReadOut(Integer bytesReadOut) {
    this.bytesReadOut = bytesReadOut;
    return this;
  }

   /**
   * Amount of bytes read out
   * @return bytesReadOut
  **/
  @ApiModelProperty(example = "5", required = true, value = "Amount of bytes read out")
  public Integer getBytesReadOut() {
    return bytesReadOut;
  }

  public void setBytesReadOut(Integer bytesReadOut) {
    this.bytesReadOut = bytesReadOut;
  }

  public CreateRunResultDto bytesTimeframeBuilder(Integer bytesTimeframeBuilder) {
    this.bytesTimeframeBuilder = bytesTimeframeBuilder;
    return this;
  }

   /**
   * What builder was used.
   * @return bytesTimeframeBuilder
  **/
  @ApiModelProperty(example = "12", required = true, value = "What builder was used.")
  public Integer getBytesTimeframeBuilder() {
    return bytesTimeframeBuilder;
  }

  public void setBytesTimeframeBuilder(Integer bytesTimeframeBuilder) {
    this.bytesTimeframeBuilder = bytesTimeframeBuilder;
  }

  public CreateRunResultDto runNumber(Integer runNumber) {
    this.runNumber = runNumber;
    return this;
  }

   /**
   * The run number.
   * @return runNumber
  **/
  @ApiModelProperty(example = "34", value = "The run number.")
  public Integer getRunNumber() {
    return runNumber;
  }

  public void setRunNumber(Integer runNumber) {
    this.runNumber = runNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRunResultDto createRunResultDto = (CreateRunResultDto) o;
    return Objects.equals(this.timeO2Start, createRunResultDto.timeO2Start) &&
        Objects.equals(this.timeTrgStart, createRunResultDto.timeTrgStart) &&
        Objects.equals(this.timeO2End, createRunResultDto.timeO2End) &&
        Objects.equals(this.timeTrgEnd, createRunResultDto.timeTrgEnd) &&
        Objects.equals(this.runType, createRunResultDto.runType) &&
        Objects.equals(this.runQuality, createRunResultDto.runQuality) &&
        Objects.equals(this.activityId, createRunResultDto.activityId) &&
        Objects.equals(this.nDetectors, createRunResultDto.nDetectors) &&
        Objects.equals(this.nFlps, createRunResultDto.nFlps) &&
        Objects.equals(this.nEpns, createRunResultDto.nEpns) &&
        Objects.equals(this.nTimeframes, createRunResultDto.nTimeframes) &&
        Objects.equals(this.nSubtimeframes, createRunResultDto.nSubtimeframes) &&
        Objects.equals(this.bytesReadOut, createRunResultDto.bytesReadOut) &&
        Objects.equals(this.bytesTimeframeBuilder, createRunResultDto.bytesTimeframeBuilder) &&
        Objects.equals(this.runNumber, createRunResultDto.runNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeO2Start, timeTrgStart, timeO2End, timeTrgEnd, runType, runQuality, activityId, nDetectors, nFlps, nEpns, nTimeframes, nSubtimeframes, bytesReadOut, bytesTimeframeBuilder, runNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRunResultDto {\n");
    
    sb.append("    timeO2Start: ").append(toIndentedString(timeO2Start)).append("\n");
    sb.append("    timeTrgStart: ").append(toIndentedString(timeTrgStart)).append("\n");
    sb.append("    timeO2End: ").append(toIndentedString(timeO2End)).append("\n");
    sb.append("    timeTrgEnd: ").append(toIndentedString(timeTrgEnd)).append("\n");
    sb.append("    runType: ").append(toIndentedString(runType)).append("\n");
    sb.append("    runQuality: ").append(toIndentedString(runQuality)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    nDetectors: ").append(toIndentedString(nDetectors)).append("\n");
    sb.append("    nFlps: ").append(toIndentedString(nFlps)).append("\n");
    sb.append("    nEpns: ").append(toIndentedString(nEpns)).append("\n");
    sb.append("    nTimeframes: ").append(toIndentedString(nTimeframes)).append("\n");
    sb.append("    nSubtimeframes: ").append(toIndentedString(nSubtimeframes)).append("\n");
    sb.append("    bytesReadOut: ").append(toIndentedString(bytesReadOut)).append("\n");
    sb.append("    bytesTimeframeBuilder: ").append(toIndentedString(bytesTimeframeBuilder)).append("\n");
    sb.append("    runNumber: ").append(toIndentedString(runNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

