/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LinkRunToLogDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-08T11:03:08.533Z")
public class LinkRunToLogDto {
  @SerializedName("runNumber")
  private Integer runNumber = null;

  public LinkRunToLogDto runNumber(Integer runNumber) {
    this.runNumber = runNumber;
    return this;
  }

   /**
   * The id of the run to link to the log.
   * @return runNumber
  **/
  @ApiModelProperty(example = "1", required = true, value = "The id of the run to link to the log.")
  public Integer getRunNumber() {
    return runNumber;
  }

  public void setRunNumber(Integer runNumber) {
    this.runNumber = runNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkRunToLogDto linkRunToLogDto = (LinkRunToLogDto) o;
    return Objects.equals(this.runNumber, linkRunToLogDto.runNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(runNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkRunToLogDto {\n");
    
    sb.append("    runNumber: ").append(toIndentedString(runNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

