/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateLogDto;
import io.swagger.client.model.LinkRunToLogDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogsApi
 */
@Ignore
public class LogsApiTest {

    private final LogsApi api = new LogsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logsGetTest() throws ApiException {
        String orderBy = null;
        String orderDirection = null;
        String pageSize = null;
        String pageNumber = null;
        String logId = null;
        String searchterm = null;
        String subtype = null;
        String origin = null;
        String startCreationTime = null;
        String endCreationTime = null;
        Object response = api.logsGet(orderBy, orderDirection, pageSize, pageNumber, logId, searchterm, subtype, origin, startCreationTime, endCreationTime);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logsIdGetTest() throws ApiException {
        Integer id = null;
        Object response = api.logsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logsIdRunsPatchTest() throws ApiException {
        LinkRunToLogDto linkRunToLogDto = null;
        Integer id = null;
        Object response = api.logsIdRunsPatch(linkRunToLogDto, id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logsPostTest() throws ApiException {
        CreateLogDto createLogDto = null;
        Object response = api.logsPost(createLogDto);

        // TODO: test validations
    }
    
}
