/*
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateRunDto;
import io.swagger.client.model.LinkLogToRunDto;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RunsApi
 */
@Ignore
public class RunsApiTest {

    private final RunsApi api = new RunsApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runsGetTest() throws ApiException {
        String orderBy = null;
        String orderDirection = null;
        String pageSize = null;
        String pageNumber = null;
        String runNumber = null;
        OffsetDateTime startTimeO2Start = null;
        OffsetDateTime endTimeO2Start = null;
        OffsetDateTime startTimeTrgStart = null;
        OffsetDateTime endTimeTrgStart = null;
        OffsetDateTime startTimeTrgEnd = null;
        OffsetDateTime endTimeTrgEnd = null;
        OffsetDateTime startTimeO2End = null;
        OffsetDateTime endTimeO2End = null;
        String activityId = null;
        Integer runType = null;
        Integer runQuality = null;
        Object response = api.runsGet(orderBy, orderDirection, pageSize, pageNumber, runNumber, startTimeO2Start, endTimeO2Start, startTimeTrgStart, endTimeTrgStart, startTimeTrgEnd, endTimeTrgEnd, startTimeO2End, endTimeO2End, activityId, runType, runQuality);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runsIdGetTest() throws ApiException {
        Integer id = null;
        Object response = api.runsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runsIdLogsPatchTest() throws ApiException {
        LinkLogToRunDto linkLogToRunDto = null;
        Integer id = null;
        Object response = api.runsIdLogsPatch(linkLogToRunDto, id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runsPostTest() throws ApiException {
        CreateRunDto createRunDto = null;
        Object response = api.runsPost(createRunDto);

        // TODO: test validations
    }
    
}
